/* tslint:disable */
/* eslint-disable */
/**
 * Eatgrim Shipping API
 * Eatgrim Shipping API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: tech@soundsgood.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Day,
    DayFromJSON,
    DayFromJSONTyped,
    DayToJSON,
    TimeRange,
    TimeRangeFromJSON,
    TimeRangeFromJSONTyped,
    TimeRangeToJSON,
} from './';

/**
 * 
 * @export
 * @interface DaySlot
 */
export interface DaySlot {
    /**
     * 
     * @type {Day}
     * @memberof DaySlot
     */
    day: Day;
    /**
     * 
     * @type {Array<TimeRange>}
     * @memberof DaySlot
     */
    timeEntries: Array<TimeRange>;
}

export function DaySlotFromJSON(json: any): DaySlot {
    return DaySlotFromJSONTyped(json, false);
}

export function DaySlotFromJSONTyped(json: any, ignoreDiscriminator: boolean): DaySlot {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'day': DayFromJSON(json['day']),
        'timeEntries': ((json['timeEntries'] as Array<any>).map(TimeRangeFromJSON)),
    };
}

export function DaySlotToJSON(value?: DaySlot | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'day': DayToJSON(value.day),
        'timeEntries': ((value.timeEntries as Array<any>).map(TimeRangeToJSON)),
    };
}


