/* tslint:disable */
/* eslint-disable */
/**
 * Eatgrim Shipping API
 * Eatgrim Shipping API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: tech@soundsgood.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Country,
    CountryFromJSON,
    CountryFromJSONTyped,
    CountryToJSON,
    DoorstepPayloadAllOf,
    DoorstepPayloadAllOfFromJSON,
    DoorstepPayloadAllOfFromJSONTyped,
    DoorstepPayloadAllOfToJSON,
    PayloadBase,
    PayloadBaseFromJSON,
    PayloadBaseFromJSONTyped,
    PayloadBaseToJSON,
} from './';

/**
 * 
 * @export
 * @interface DoorstepPayload
 */
export interface DoorstepPayload {
    /**
     * 
     * @type {Country}
     * @memberof DoorstepPayload
     */
    country: Country;
    /**
     * Shopify product id
     * @type {string}
     * @memberof DoorstepPayload
     */
    pilotId: string;
    /**
     * 
     * @type {number}
     * @memberof DoorstepPayload
     */
    timeEntryId?: number;
    /**
     * 
     * @type {string}
     * @memberof DoorstepPayload
     */
    zipCode?: string;
}

export function DoorstepPayloadFromJSON(json: any): DoorstepPayload {
    return DoorstepPayloadFromJSONTyped(json, false);
}

export function DoorstepPayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): DoorstepPayload {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'country': CountryFromJSON(json['country']),
        'pilotId': json['pilotId'],
        'timeEntryId': !exists(json, 'timeEntryId') ? undefined : json['timeEntryId'],
        'zipCode': !exists(json, 'zipCode') ? undefined : json['zipCode'],
    };
}

export function DoorstepPayloadToJSON(value?: DoorstepPayload | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'country': CountryToJSON(value.country),
        'pilotId': value.pilotId,
        'timeEntryId': value.timeEntryId,
        'zipCode': value.zipCode,
    };
}


