/* tslint:disable */
/* eslint-disable */
/**
 * Eatgrim Shipping API
 * Eatgrim Shipping API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: tech@soundsgood.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DoorstepDeliveryLocationAllOf
 */
export interface DoorstepDeliveryLocationAllOf {
    /**
     * 
     * @type {string}
     * @memberof DoorstepDeliveryLocationAllOf
     */
    zipCode: string;
}

export function DoorstepDeliveryLocationAllOfFromJSON(json: any): DoorstepDeliveryLocationAllOf {
    return DoorstepDeliveryLocationAllOfFromJSONTyped(json, false);
}

export function DoorstepDeliveryLocationAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): DoorstepDeliveryLocationAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'zipCode': json['zipCode'],
    };
}

export function DoorstepDeliveryLocationAllOfToJSON(value?: DoorstepDeliveryLocationAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'zipCode': value.zipCode,
    };
}


