/* tslint:disable */
/* eslint-disable */
/**
 * Eatgrim Shipping API
 * Eatgrim Shipping API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: tech@soundsgood.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DoorstepPayloadAllOf
 */
export interface DoorstepPayloadAllOf {
    /**
     * 
     * @type {number}
     * @memberof DoorstepPayloadAllOf
     */
    timeEntryId?: number;
    /**
     * 
     * @type {string}
     * @memberof DoorstepPayloadAllOf
     */
    zipCode?: string;
}

export function DoorstepPayloadAllOfFromJSON(json: any): DoorstepPayloadAllOf {
    return DoorstepPayloadAllOfFromJSONTyped(json, false);
}

export function DoorstepPayloadAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): DoorstepPayloadAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'timeEntryId': !exists(json, 'timeEntryId') ? undefined : json['timeEntryId'],
        'zipCode': !exists(json, 'zipCode') ? undefined : json['zipCode'],
    };
}

export function DoorstepPayloadAllOfToJSON(value?: DoorstepPayloadAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'timeEntryId': value.timeEntryId,
        'zipCode': value.zipCode,
    };
}


