/* tslint:disable */
/* eslint-disable */
/**
 * Eatgrim Shipping API
 * Eatgrim Shipping API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: tech@soundsgood.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    DateSlot,
    DateSlotFromJSON,
    DateSlotFromJSONTyped,
    DateSlotToJSON,
} from './';

/**
 * 
 * @export
 * @interface LocationBase
 */
export interface LocationBase {
    /**
     * 
     * @type {number}
     * @memberof LocationBase
     */
    id: number;
    /**
     * 
     * @type {number}
     * @memberof LocationBase
     */
    price: number;
    /**
     * 
     * @type {Array<DateSlot>}
     * @memberof LocationBase
     */
    slots: Array<DateSlot>;
}

export function LocationBaseFromJSON(json: any): LocationBase {
    return LocationBaseFromJSONTyped(json, false);
}

export function LocationBaseFromJSONTyped(json: any, ignoreDiscriminator: boolean): LocationBase {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'price': json['price'],
        'slots': ((json['slots'] as Array<any>).map(DateSlotFromJSON)),
    };
}

export function LocationBaseToJSON(value?: LocationBase | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'price': value.price,
        'slots': ((value.slots as Array<any>).map(DateSlotToJSON)),
    };
}


