/* tslint:disable */
/* eslint-disable */
/**
 * Eatgrim Shipping API
 * Eatgrim Shipping API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: tech@soundsgood.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Country,
    CountryFromJSON,
    CountryFromJSONTyped,
    CountryToJSON,
} from './';

/**
 * 
 * @export
 * @interface PayloadBase
 */
export interface PayloadBase {
    /**
     * 
     * @type {Country}
     * @memberof PayloadBase
     */
    country: Country;
    /**
     * Shopify product id
     * @type {string}
     * @memberof PayloadBase
     */
    shopifyProductId: string;
}

export function PayloadBaseFromJSON(json: any): PayloadBase {
    return PayloadBaseFromJSONTyped(json, false);
}

export function PayloadBaseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PayloadBase {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'country': CountryFromJSON(json['country']),
        'shopifyProductId': json['shopifyProductId'],
    };
}

export function PayloadBaseToJSON(value?: PayloadBase | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'country': CountryToJSON(value.country),
        'shopifyProductId': value.shopifyProductId,
    };
}


