/* tslint:disable */
/* eslint-disable */
/**
 * Eatgrim Shipping API
 * Eatgrim Shipping API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: tech@soundsgood.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Address,
    AddressFromJSON,
    AddressFromJSONTyped,
    AddressToJSON,
    Coordinates,
    CoordinatesFromJSON,
    CoordinatesFromJSONTyped,
    CoordinatesToJSON,
    DaySlot,
    DaySlotFromJSON,
    DaySlotFromJSONTyped,
    DaySlotToJSON,
} from './';

/**
 * 
 * @export
 * @interface PickupLocationAllOf
 */
export interface PickupLocationAllOf {
    /**
     * 
     * @type {string}
     * @memberof PickupLocationAllOf
     */
    name: string;
    /**
     * 
     * @type {Address}
     * @memberof PickupLocationAllOf
     */
    address: Address;
    /**
     * 
     * @type {Coordinates}
     * @memberof PickupLocationAllOf
     */
    coordinates: Coordinates;
    /**
     * 
     * @type {Array<DaySlot>}
     * @memberof PickupLocationAllOf
     */
    openingHours?: Array<DaySlot>;
}

export function PickupLocationAllOfFromJSON(json: any): PickupLocationAllOf {
    return PickupLocationAllOfFromJSONTyped(json, false);
}

export function PickupLocationAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): PickupLocationAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'address': AddressFromJSON(json['address']),
        'coordinates': CoordinatesFromJSON(json['coordinates']),
        'openingHours': !exists(json, 'openingHours') ? undefined : ((json['openingHours'] as Array<any>).map(DaySlotFromJSON)),
    };
}

export function PickupLocationAllOfToJSON(value?: PickupLocationAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'address': AddressToJSON(value.address),
        'coordinates': CoordinatesToJSON(value.coordinates),
        'openingHours': value.openingHours === undefined ? undefined : ((value.openingHours as Array<any>).map(DaySlotToJSON)),
    };
}


