/* tslint:disable */
/* eslint-disable */
/**
 * Eatgrim Shipping API
 * Eatgrim Shipping API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: tech@soundsgood.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Coordinates,
    CoordinatesFromJSON,
    CoordinatesFromJSONTyped,
    CoordinatesToJSON,
} from './';

/**
 * 
 * @export
 * @interface PickupPayloadAllOf
 */
export interface PickupPayloadAllOf {
    /**
     * 
     * @type {number}
     * @memberof PickupPayloadAllOf
     */
    id?: number;
    /**
     * 
     * @type {Coordinates}
     * @memberof PickupPayloadAllOf
     */
    currentPosition?: Coordinates;
}

export function PickupPayloadAllOfFromJSON(json: any): PickupPayloadAllOf {
    return PickupPayloadAllOfFromJSONTyped(json, false);
}

export function PickupPayloadAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): PickupPayloadAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'currentPosition': !exists(json, 'currentPosition') ? undefined : CoordinatesFromJSON(json['currentPosition']),
    };
}

export function PickupPayloadAllOfToJSON(value?: PickupPayloadAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'currentPosition': CoordinatesToJSON(value.currentPosition),
    };
}


