/* tslint:disable */
/* eslint-disable */
/**
 * Eatgrim Shipping API
 * Eatgrim Shipping API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: tech@soundsgood.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TimeEntryAllOf
 */
export interface TimeEntryAllOf {
    /**
     * 
     * @type {number}
     * @memberof TimeEntryAllOf
     */
    id: number;
    /**
     * Availability of the time entry
     * @type {boolean}
     * @memberof TimeEntryAllOf
     */
    available: boolean;
    /**
     * 
     * @type {string}
     * @memberof TimeEntryAllOf
     */
    description?: string;
    /**
     * Shopify variant id
     * @type {string}
     * @memberof TimeEntryAllOf
     */
    variantId: string;
}

export function TimeEntryAllOfFromJSON(json: any): TimeEntryAllOf {
    return TimeEntryAllOfFromJSONTyped(json, false);
}

export function TimeEntryAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): TimeEntryAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'available': json['available'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'variantId': json['variantId'],
    };
}

export function TimeEntryAllOfToJSON(value?: TimeEntryAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'available': value.available,
        'description': value.description,
        'variantId': value.variantId,
    };
}


