/* tslint:disable */
/* eslint-disable */
/**
 * Eatgrim Shipping API
 * Eatgrim Shipping API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: tech@soundsgood.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Country,
    CountryFromJSON,
    CountryFromJSONTyped,
    CountryToJSON,
    PayloadBase,
    PayloadBaseFromJSON,
    PayloadBaseFromJSONTyped,
    PayloadBaseToJSON,
} from './';

/**
 * 
 * @export
 * @interface TypePayload
 */
export interface TypePayload {
    /**
     * 
     * @type {Country}
     * @memberof TypePayload
     */
    country: Country;
    /**
     * Shopify product id
     * @type {string}
     * @memberof TypePayload
     */
    pilotId: string;
}

export function TypePayloadFromJSON(json: any): TypePayload {
    return TypePayloadFromJSONTyped(json, false);
}

export function TypePayloadFromJSONTyped(json: any, ignoreDiscriminator: boolean): TypePayload {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'country': CountryFromJSON(json['country']),
        'pilotId': json['pilotId'],
    };
}

export function TypePayloadToJSON(value?: TypePayload | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'country': CountryToJSON(value.country),
        'pilotId': value.pilotId,
    };
}


